spring.application.name=reality
# Server port
server.port=8081

# Database (file-based)
spring.datasource.url=jdbc:postgresql://localhost:5432/reality
spring.datasource.username=postgres
spring.datasource.password=Tiger

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect